---
- name: Create a data container
  docker_container:
    name: mydata
    image: busybox
    volumes:
      - /data
    state: started

- name: Start r3lik 
  docker_container:
    name: r3lik
    image: r3lik/catnip
    published_ports: 0.0.0.0:1337:5000
